server:
  port: 8083

spring:
  application:
    name: admin-service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ru.cupofmilk: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    tech.ailef.snapadmin: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

snapadmin:
  enabled: true
  baseUrl: admin
  modelsPackage: ru.cupofmilk.model
  internal-db:
    enabled: false